### ISSUE TITLE
Start/stop codon

### ISSUE THREAD

**Issue by lskatz** [lskatz/mlst-hash-template#9]
Add a standard attribute if the start and/or stop codon is present in the allele

**Comment by chrisgulvik** [comment]
The value here with codons specified are that certain cgMLST callers might expect only certain codons as a verification the gene is fully intact.

An additional feature option to consider would be gene length (in basepairs). Unsure if this is a valuable addition or makes it unnecessarily complicated though.

**Comment by lskatz** [comment]
Might need to think of indels.  Could use a CIGAR string?
